MQTT_CONNECT_CMDS = "commands/MQTT_CONNECT.txt"
PDP_ACTIVATE_CMDS = "commands/PDP_ACTIVATE.txt"
PORT = "COM49"
BAUD = 9600  # Note: BAUD is now an integer
PUBLISH_TOPIC = "devices/EG916Q_01/status"
ACCEPTED_RESPONSES = ["OK", "CONNECT"]
